In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]]
])

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[  1   2   0]
  [  3   5   1]]

 [[  4 322   1]
  [345  21  21]]

 [[ 65  32  77]
  [ 21  46  89]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(3, 2, 3)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]],
     [[1,2,0],
     [12,34,77]]],
    [[[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]],
     [[1,2,0],
     [12,34,77]]],
    [[[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]],
     [[1,2,0],
     [12,34,77]]]
])

In [ ]:
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5   1]]

  [[  4 322   1]
   [345  21  21]]

  [[ 65  32  77]
   [ 21  46  89]]

  [[  1   2   0]
   [ 12  34  77]]]


 [[[  1   2   0]
   [  3   5   1]]

  [[  4 322   1]
   [345  21  21]]

  [[ 65  32  77]
   [ 21  46  89]]

  [[  1   2   0]
   [ 12  34  77]]]


 [[[  1   2   0]
   [  3   5   1]]

  [[  4 322   1]
   [345  21  21]]

  [[ 65  32  77]
   [ 21  46  89]]

  [[  1   2   0]
   [ 12  34  77]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
tensor_four_d.ndim

4

In [ ]:
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_one_d.ndim

1

In [ ]:
import numpy as np

In [ ]:
##convering array into tensors

np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
np_array.shape

(4,)

In [ ]:
ct = tf.convert_to_tensor(np_array)
print(ct)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
type(ct)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
im = tf.eye(3,batch_shape=[2])
print(im)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
tf.shape(im)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 3], dtype=int32)>

In [ ]:
print(tf.shape(tensor_four_d
         ))

tf.Tensor([3 4 2 3], shape=(4,), dtype=int32)


In [ ]:
tf.rank(im)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
random_t = tf.random.normal([3,2],100,100)

In [ ]:
print(random_t)

tf.Tensor(
[[ 88.79649  170.83241 ]
 [100.81504   55.634056]
 [132.63045   55.276623]], shape=(3, 2), dtype=float32)


In [ ]:
ran_t = tf.random.uniform([4,5])

In [ ]:
print(ran_t)

tf.Tensor(
[[0.58210146 0.81507874 0.06345975 0.9933045  0.8088434 ]
 [0.20589364 0.59493375 0.1389848  0.48725688 0.4609952 ]
 [0.3796401  0.2822442  0.37817025 0.2983395  0.9490334 ]
 [0.23017478 0.55396783 0.4233501  0.4399948  0.49963593]], shape=(4, 5), dtype=float32)


In [ ]:
for x in range(5):
  print(x)

0
1
2
3
4


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
print(tensor_two_d[1:3,0])

tf.Tensor([3 1], shape=(2,), dtype=int32)


In [ ]:
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]]
])

print(tensor_three_d)

tf.Tensor(
[[[  1   2   0]
  [  3   5   1]]

 [[  4 322   1]
  [345  21  21]]

 [[ 65  32  77]
  [ 21  46  89]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d[0:2,0,0:1])

tf.Tensor(
[[1]
 [4]], shape=(2, 1), dtype=int32)


In [ ]:
x = tf.constant([-22,-21,-33])
tf.abs(x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 21, 33], dtype=int32)>

In [ ]:
x1 = tf.constant([[1,2,0],[2,3,4]])
x2 = tf.constant([[1,2],[2,2],[5,6]])

In [ ]:
tf.linalg.matmul(x1,x2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [28, 34]], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,1]],
    [[4,322,1],
     [345,21,21]],
    [[65,32,77],
     [21,46,89]]
])

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[  1   2   0]
  [  3   5   1]]

 [[  4 322   1]
  [345  21  21]]

 [[ 65  32  77]
  [ 21  46  89]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tf.expand_dims(tensor_three_d,axis=1)

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[  1,   2,   0],
         [  3,   5,   1]]],


       [[[  4, 322,   1],
         [345,  21,  21]]],


       [[[ 65,  32,  77],
         [ 21,  46,  89]]]], dtype=int32)>

In [ ]:
ex = tf.expand_dims(tensor_three_d,axis=0)

In [ ]:
print(ex.shape)

(1, 3, 2, 3)


In [ ]:
tf.reshape(ex,[3,2,3])

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   0],
        [  3,   5,   1]],

       [[  4, 322,   1],
        [345,  21,  21]],

       [[ 65,  32,  77],
        [ 21,  46,  89]]], dtype=int32)>

In [ ]:
tf.reshape(ex,[2,3,3])

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[  1,   2,   0],
        [  3,   5,   1],
        [  4, 322,   1]],

       [[345,  21,  21],
        [ 65,  32,  77],
        [ 21,  46,  89]]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2,3],
                 [4,5,6]])

y = tf.constant([
    [1,2],
    [3,4]
])

In [ ]:
print(tf.pad(x,y,'constant'))

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
